### ISSUE TITLE
[0.9.2.1 BETA] Invalid bitcode signature error when archiving in XCode

### ISSUE THREAD

**Issue by lucasholucasho** [sturfeeinc/Sturfee.Unity.XR-issues#4]
Description

1. Build in Unity with iOS as the target platform
2. Open in Xcode and archive with "Generic iOS Device" as the build target

Expected: archives with no errors
Actual: Invalid bitcode signature error causes archiving to fail [Apple Mach-O Linker (ld) Error: error: Invalid bitcode signature, clang: error: linker command failed with exit code 1 (use -v to see invocation)]

The error goes away when the "Build Active Architecture Only" flag is set to yes and the build target is my iPhone (iPhone 8 running iOS 11.3.1), but this means that users with iPhones that have different architectures won't be compatible with the build. Users have told me they've run in to this issue, which makes this a release blocker. Other developers may encounter this too - I'd appreciate it if this could be expedited - thanks!

Environment
Unity Version: 2017.3.1f1 Personal / OS: Mac OS High Sierra 10.13.5 / SDK Version: 0.9.2.1 / Xcode Version: 9.3.1

**Comment by pducks32** [comment]
Hi @lucasholucasho,

Thanks for the issue and the great bug report and sorry that you encountered it. I'll be looking into this today and will update you as soon as we have solved it.

**Comment by lucasholucasho** [comment]
@pducks32 @kushG this issue can be closed since it's been fixed in the newest beta - thanks! (with the caveat that you need to delete the Arkit and Arcore folders for it to support older phones)
